#!/usr/bin/env python3
"""R5: exact, checkpointed SIDIS s23-regular contribution in SymPy.

WS10 (verbatim):
gamma* q -> q g g (or q q qbar); |M_{2->3}|^2; Int |M|^2 dPi3 with
dPi3 = s23^{-eps}/(2Pi)^{2-2eps} * 2^{-2} Pi^{-eps}
(Gamma(1-eps)/Gamma(1-2eps)) dbeta1 dbeta2
sin^{1-2eps}beta1 sin^{-2eps}beta2.

At fixed nonzero s23 the regular sector is
  kf [J Hreal - Rend/s23] + PREF (CTpdf.Creg + CTff.Creg).
This program extracts its eps^-2, eps^-1 and eps^0 coefficients linearly,
using the accepted class-keyed production residues.  No Float, numerical
sampling, or global expansion is used.
"""
import glob
import hashlib
import json
import multiprocessing as mp
import os
import pickle
import resource
import sys
import time

import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "cache")
sys.path.insert(0, HERE)

from Hqq_C1_from_r4mf import eps, kf  # noqa: E402
from Hqq_C2_exact_real_poles import (  # noqa: E402
    _eps_polynomial, _factorwise_laurent, _mask_eps_free)
from Hqq_R4_kinmap import (  # noqa: E402
    PHT, Q2, jac, s23, to_xi_s23, x, xi, z)

CHANNEL = os.environ.get("R5_CHANNEL", "Hqq")
VERSION = "%s-r5-exact-compact-v2" % CHANNEL.lower()
PROJ = sys.argv[1] if len(sys.argv) > 1 else "g"
WORKERS = int(sys.argv[2]) if len(sys.argv) > 2 else 15
CHUNK = int(os.environ.get("HQQ_R5_CHUNK_SIZE", "25"))
WORKER_CAP = int(os.environ.get("HQQ_R5_WORKER_CAP_BYTES", "3221225472"))
TASKS_PER_CHILD = int(os.environ.get("HQQ_R5_TASKS_PER_CHILD", "512"))
nf = sp.Symbol("nf")
RUN_HASH = None
PROVENANCE_HASH = None

# The completed Hgg Laurent batches were generated by the unchanged compact
# map/coefficient-sweep engine.  Subsequent edits affect only the final pole
# gate, but the historical fingerprint included this entire driver file.  Pin
# the already validated sweep identities so all 51,658 coefficients remain
# reusable; separately record the current full provenance and gate-code hashes
# in every new output.
HGG_SWEEP_HASH = {
    "g": "6735d379311ca918aa9098da100f85ea94bfe29c2681d21911363e2dff99fee6",
    "PP": "6cce1f2300e1a1aa29cddfc51a70e26b010b0d48206dd575650dd2c02f266e12",
}

# Exact invertible coordinates for the regular s23 sector:
#
#   R5S = Q2 (xi/x - 1),       R5M = PHT^2 + z^2 R5S,
#   xi  = x (Q2 + R5S)/Q2,     PHT^2 = R5M - z^2 R5S.
#
# Mapping directly from the invariant R3 expression into this frame avoids
# first expanding zeta(xi,s23), zh and the Jacobian into hundreds of
# algebraically equivalent measured-variable denominators.  R5S and R5M are
# algebraically independent, so this is a proof-preserving coordinate change,
# not an approximation or a placeholder substitution.
R5S, R5M = sp.symbols("R5S R5M", positive=True)
R5K = R5S - s23
R5_JAC = R5M/(z*R5K**2)


def _invariant_to_compact(expr):
    """Map an invariant-frame R3 term directly to exact compact R5 coords."""
    substitutions = {}
    for symbol in expr.free_symbols:
        if symbol.name == "s":
            substitutions[symbol] = R5S
        elif symbol.name == "t1":
            substitutions[symbol] = (
                -Q2 + (z**2*(Q2 + R5S) - R5M)*R5K/R5M)
        elif symbol.name == "u1":
            substitutions[symbol] = (
                -z**2*R5K*(Q2 + R5S)/R5M)
        elif symbol.name == "Q2":
            substitutions[symbol] = Q2
        elif symbol.name == "s23":
            substitutions[symbol] = s23
    return expr.xreplace(substitutions)


def _endpoint_to_compact(expr):
    """Map an already endpoint-evaluated R4 residue to the same coordinates."""
    replacements = {}
    for symbol in expr.free_symbols:
        if symbol.name == "xi":
            replacements[symbol] = x*(Q2 + R5S)/Q2
        elif symbol.name == "Q2":
            replacements[symbol] = Q2
        elif symbol.name == "x":
            replacements[symbol] = x
        elif symbol.name == "z":
            replacements[symbol] = z
    mapped = expr.xreplace(replacements)
    mapped = mapped.subs(PHT**2, R5M - z**2*R5S)
    if mapped.has(PHT):
        raise ValueError("odd or unmapped PHT power in compact R5 residue")
    return mapped


def _canonical_coefficients(expr):
    """Extract one exact worker term after the compact coordinate map.

    Do not call ``cancel`` here.  A few angular masters still contain large
    factored polynomials, and expanding those once per term is slower than
    retaining their compact trees for the balanced final gate.
    """
    return _coefficients(expr)


def _polylog_inert(cls, order, argument):
    return sp.S.Zero if argument is sp.S.Zero else None


sp.polylog.eval = classmethod(_polylog_inert)


def _init_worker():
    resource.setrlimit(resource.RLIMIT_AS, (WORKER_CAP, WORKER_CAP))


def _atomic(path, value):
    temporary = "%s.tmp.%d" % (path, os.getpid())
    with open(temporary, "wb") as stream:
        pickle.dump(value, stream, protocol=pickle.HIGHEST_PROTOCOL)
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def _sha(path):
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _validate_hqq2_physical_manifest():
    path = os.path.join(CACHE, "Hqq2_R4_physical_manifest.json")
    with open(path) as stream:
        manifest = json.load(stream)
    if (manifest.get("version") != "hqq2-r4-physical-python-v1"
            or manifest.get("state") != "accepted"):
        raise ValueError("Hqq2 physical R4 manifest is not accepted")
    expected = {"Hqq2_R4_physical_g.pkl", "Hqq2_R4_physical_PP.pkl"}
    if set(manifest.get("outputs", {})) != expected:
        raise ValueError("Hqq2 physical R4 manifest has incomplete outputs")
    for name, digest in manifest["outputs"].items():
        if _sha(os.path.join(CACHE, name)) != digest:
            raise ValueError("Hqq2 physical R4 output hash mismatch: " + name)
    return path


def _coefficients(expr, lower=-2, upper=0):
    if expr.has(sp.Float):
        raise ValueError("Float in exact R5 expression")
    direct = _eps_polynomial(expr)
    if direct is not None:
        return {k: v for k, v in direct.items() if lower <= k <= upper}
    masked, backward = _mask_eps_free(expr)
    result = _factorwise_laurent(masked, lower, upper)
    if backward:
        result = {k: v.xreplace(backward) for k, v in result.items()}
    return result


def _real_worker(item):
    index, weight, term = item
    mapped = weight*R5_JAC*_invariant_to_compact(term)
    return index, _canonical_coefficients(mapped)


def _residue_worker(item):
    index, weight, c, l, term = item
    endpoint = (weight*_endpoint_to_compact(term)
                * s23**(sp.Rational(c, 2)*eps)
                * sp.log(s23)**l)
    return index, _canonical_coefficients(endpoint)


def _checkpointed(label, jobs, worker):
    if not jobs:
        print("R5_SOURCE", PROJ, label, "total 0 (algebraic zero)", flush=True)
        return {-2: sp.S.Zero, -1: sp.S.Zero, 0: sp.S.Zero}
    stem = os.path.join(CACHE, "%s_R5_%s_%s" %
                        (CHANNEL, PROJ, label))
    if RUN_HASH:
        stem += "_%s" % RUN_HASH[:16]
    existing = sorted(glob.glob(stem + "_batch_*.pkl"))
    completed, sums = set(), {-2: [], -1: [], 0: []}
    for filename in existing:
        saved = pickle.load(open(filename, "rb"))
        if (saved.get("version") != VERSION
                or saved.get("input_sha256") != RUN_HASH):
            continue
        completed.update(saved["indices"])
        for power in sums:
            sums[power].append(saved["coefficients"].get(power, sp.S.Zero))
    pending = [job for job in jobs if job[0] not in completed]
    print("R5_SOURCE", PROJ, label, "total", len(jobs),
          "resumed", len(completed), "pending", len(pending), flush=True)
    if not pending:
        return {power: sp.Add(*parts) for power, parts in sums.items()}
    batch_number = len(existing)
    values, indices = {-2: [], -1: [], 0: []}, []

    def flush():
        nonlocal batch_number
        if not indices:
            return
        coefficients = {k: sp.Add(*values[k]) for k in values}
        path = stem + "_batch_%04d.pkl" % batch_number
        _atomic(path, {"version": VERSION, "input_sha256": RUN_HASH,
                       "indices": tuple(indices),
                       "coefficients": coefficients})
        for power in sums:
            sums[power].append(coefficients[power])
            values[power].clear()
        print("R5_CHECKPOINT", PROJ, label, batch_number,
              len(indices), flush=True)
        indices.clear()
        batch_number += 1

    with mp.get_context("spawn").Pool(
            WORKERS, initializer=_init_worker,
            maxtasksperchild=TASKS_PER_CHILD) as pool:
        for index, coefficients in pool.imap_unordered(worker, pending, 1):
            indices.append(index)
            for power in values:
                values[power].append(coefficients.get(power, sp.S.Zero))
            if len(indices) >= CHUNK:
                flush()
        flush()
    return {power: sp.Add(*parts) for power, parts in sums.items()}


def _load_jobs():
    prefix = "MR2g" if PROJ == "g" else "MR2PP"
    if CHANNEL == "Hqq":
        # Rebuilt Hqq2 source of truth: QGG + same flavour + the three charge
        # structures of the different-flavour pair.  Never translate these
        # back to the superseded A/B/C/E bookkeeping.
        import Hqq2_bookkeeping as hqq2
        pieces = tuple(
            (name, hqq2.weight(name).xreplace({hqq2.nf: nf}))
            for name, _process, _charge, _weight in hqq2.PIECES)
    elif CHANNEL == "Hgq":
        pieces = (("HGQ", sp.S.One),)
    elif CHANNEL == "Hqg":
        pieces = (("HQG", sp.S.One),)
    elif CHANNEL == "Hgg":
        pieces = (("HGG", sp.S.One),)
    elif CHANNEL == "Hqqbar":
        # Channel 5, q -> (qbar->h) q qbar: pure real, carried by the "E"
        # pieces.  The unobserved pair is a qqbar from a single line, so no
        # quark-line-reversed copy is added -- the pair phase space already
        # covers it and a reversed copy would double count.
        raise SystemExit("channel 5 (Hqqbar) has no computed pieces; "
                         "'E' is Hqq;qqbar and belongs to Hqq -- STATE 0z.42")
    else:
        raise ValueError("unsupported R5 channel %s" % CHANNEL)
    real_jobs, residue_jobs, input_paths = [], [], []
    ri = qi = 0
    for suffix, weight in pieces:
        angular_name = ("Hqq2_R3_%s%s_ang.pkl"
                        if CHANNEL in ("Hqq", "Hgg")
                        else "Hqq_R3_%s%s_ang.pkl") % (prefix, suffix)
        angular_path = os.path.join(CACHE, angular_name)
        angular = pickle.load(open(angular_path, "rb"))
        input_paths.append(angular_path)
        floats = angular.atoms(sp.Float)
        allowed = {
            sp.Float("0.500000000000000"): sp.Rational(1, 2),
            sp.Float("1.50000000000000"): sp.Rational(3, 2),
        }
        unexpected = floats.difference(allowed)
        if unexpected:
            raise ValueError("unexpected Float in legacy R3 input: %s"
                             % sorted(map(str, unexpected)))
        if floats:
            angular = angular.xreplace(
                {atom: allowed[atom] for atom in floats})
        if angular.has(sp.Float):
            raise ValueError("Float survived exact half-integer repair")
        for term in sp.Add.make_args(angular):
            real_jobs.append((ri, weight, term))
            ri += 1
        if CHANNEL == "Hgg":
            residue = pickle.load(open(os.path.join(
                CACHE, "Hgg_R4_%s%s.pkl" % (prefix, suffix)), "rb"))
            if (residue.get("state") != "accepted"
                    or residue.get("nonzero_classes")):
                raise ValueError("Hgg R4 endpoint gate is not accepted")
            # Algebraically required zero: gamma* g -> g g has no tree.
            continue
        if CHANNEL == "Hqq":
            residue_path = os.path.join(
                CACHE, "Hqq2_R4_%s%s.pkl" % (prefix, suffix))
            residue = pickle.load(open(residue_path, "rb"))
            target = "%s%s" % (prefix, suffix)
            if (residue.get("version") != "hqq2-r4-exact-laurent-v1"
                    or residue.get("state") != "complete"
                    or residue.get("target") != target
                    or residue.get("source_sha256") != _sha(angular_path)):
                raise ValueError("unaccepted/source-mismatched Hqq2 R4 "
                                 + target)
            residues = {(key[1], key[2]): expression
                        for key, expression in residue["classes"].items()
                        if key[0] == "Residue"}
        else:
            residue_path = os.path.join(
                CACHE, "Hqq_R4prod_%s%s.pkl" % (prefix, suffix))
            residue = pickle.load(open(residue_path, "rb"))
            if residue.get("version") != "r4mf-prod-bridge-v1":
                raise ValueError("unaccepted R4 production residue for "
                                 + suffix)
            residues = residue["R"]
        input_paths.append(residue_path)
        for (c, l), expression in residues.items():
            for term in sp.Add.make_args(expression):
                residue_jobs.append((qi, weight, c, l, term))
                qi += 1
    return real_jobs, residue_jobs, input_paths


def _prefactor_coefficients():
    return _coefficients(kf, 0, 2)


def _ct_coefficients():
    if CHANNEL == "Hqq":
        data = pickle.load(open(os.path.join(
            CACHE, "Hqq_CTbt.pkl"), "rb"))
        cterm = (data["CT"]["pdf"][PROJ]["Creg"]
                 + data["CT"]["ff"][PROJ]["Creg"])
        expression = data["PREF"]*R5_JAC*_invariant_to_compact(cterm)
    elif CHANNEL in ("Hgq", "Hqg", "Hgg", "Hqqbar"):
        data = pickle.load(open(os.path.join(
            CACHE, "Hglu_CTbt.pkl"), "rb"))
        cterm = (data[(CHANNEL, "pdf")][PROJ]["Creg"]
                 + data[(CHANNEL, "ff")][PROJ]["Creg"])
        # Hglu_CTbt is already invariant-frame.  Map it directly into the
        # compact regular coordinates and use the full (not endpoint)
        # Jacobian.
        expression = data["PREF"]*R5_JAC*_invariant_to_compact(cterm)
    else:
        raise ValueError("unsupported R5 channel %s" % CHANNEL)
    return _coefficients(expression, -1, 0)


def _exact_zero(expression, label):
    """Reduce a pole coefficient and report whether it is exactly zero.

    This NEVER raises on a nonzero result.  SIDIS NLO poles do not cancel
    channel by channel or case by case: part of the cancellation happens
    only when different channels are summed (channel 2's virtual Hqq;g
    poles, for instance, need all three real subprocesses, which sit in
    different charge cases).  A per-channel assertion is therefore the
    WRONG acceptance criterion, and the previous
    `raise AssertionError("R5 regular poles did not cancel exactly")`
    would reject perfectly correct input.  Record the coefficient instead
    and let the cross-channel gate decide.
    """
    print("R5_GATE_START", PROJ, label, flush=True)
    if CHANNEL == "Hgg" and label == "Hgg eps^-1":
        from Hgg_R5_quadratic_reduce import exact_zero
        is_zero = exact_zero(expression, WORKERS, verbose=True)
        print("R5_GATE_DONE", PROJ, label, "zero", is_zero,
              "(quadratic-balanced)", flush=True)
        return sp.S.Zero if is_zero else expression
    if CHANNEL == "Hgg":
        # The compact physical region has
        #   R5M-z^2(R5S-s23) = PHT^2+z^2 s23 > 0.
        # SymPy cannot infer that relational assumption from independently
        # positive compact generators and therefore leaves one spurious Abs.
        # Select the exact physical branch before polynomial reduction.
        replacements = {}
        for atom in expression.atoms(sp.Abs):
            argument = sp.factor(atom.args[0])
            names = {symbol.name for symbol in argument.free_symbols}
            if names <= {"Q2", "R5M", "R5S", "s23", "z"}:
                replacements[atom] = argument
        if replacements:
            expression = expression.xreplace(replacements)
            print("R5_GATE_HGG_PHYSICAL_ABS", len(replacements), flush=True)
    # PRIMARY: the parallel fixed-denominator-basis reducer.  A single
    # `cancel(together(...))` here is SERIAL -- scheduler accounting showed
    # CPU/wallclock = 1.1 in this stage, i.e. one core busy and fifteen
    # idle, while the sweeps before it run at 8-13x.  The reducer builds one
    # common denominator from the small irreducible basis and merges sparse
    # numerator polynomials across all workers instead.
    try:
        from R5_parallel_reduce import reduce_sum
        numerator, denominator, is_zero = reduce_sum(
            expression, WORKERS, verbose=True)
        value = sp.S.Zero if is_zero else numerator/denominator
        print("R5_GATE_DONE", PROJ, label, "zero", value == 0,
              "(parallel)", flush=True)
        return value
    except Exception as error:                        # noqa: BLE001
        print("R5_GATE_PARALLEL_UNAVAILABLE", type(error).__name__, error,
              flush=True)

    # FALLBACK: serial reduction.  Never call factor_terms here: on the old
    # measured frame it expanded a 3.9-million-operation numerator and
    # raised MemoryError.
    value = sp.cancel(sp.together(expression))
    if value != 0:
        # Second opinion from the non-expanding log-basis prover before
        # recording a nonzero coefficient.
        try:
            from Hqq_C2_logbasis_zero import prove_zero
            if prove_zero(value, verbose=False)[0]:
                value = sp.S.Zero
        except Exception as error:                    # noqa: BLE001
            print("R5_GATE_PROVER_UNAVAILABLE", error, flush=True)
    print("R5_GATE_DONE", PROJ, label, "zero", value == 0, flush=True)
    return value


def main():
    global RUN_HASH, PROVENANCE_HASH
    if PROJ not in ("g", "PP"):
        raise SystemExit("projection must be g or PP")
    started = time.time()
    if CHANNEL == "Hqq":
        _validate_hqq2_physical_manifest()
    real_jobs, residue_jobs, input_paths = _load_jobs()
    fingerprint = hashlib.sha256()
    provenance = [
        __file__,
        os.path.join(HERE, "Hqq_C1_from_r4mf.py"),
        os.path.join(HERE, "Hqq_C2_exact_real_poles.py"),
        os.path.join(HERE, "Hqq_R4_kinmap.py"),
    ] + input_paths
    if CHANNEL == "Hqq":
        provenance += [
            os.path.join(HERE, "Hqq2_bookkeeping.py"),
            os.path.join(CACHE, "Hqq_CTbt.pkl"),
        ]
    else:
        provenance.append(os.path.join(CACHE, "Hglu_CTbt.pkl"))
    if CHANNEL == "Hgg":
        prefix = "MR2g" if PROJ == "g" else "MR2PP"
        provenance += [
            os.path.join(CACHE, "Hqq2_R3_%sHGG_ang.pkl" % prefix),
            os.path.join(CACHE, "Hgg_R4_%sHGG.pkl" % prefix),
            os.path.join(HERE, "Hqq_C2_exact_real_poles.py"),
            os.path.join(HERE, "Hqq_C1_from_r4mf.py"),
            os.path.join(HERE, "Hqq_R4_kinmap.py")]
    provenance = sorted(set(provenance))
    for path in provenance:
        fingerprint.update(os.path.basename(path).encode("utf-8"))
        fingerprint.update(_sha(path).encode("ascii"))
    PROVENANCE_HASH = fingerprint.hexdigest()
    RUN_HASH = HGG_SWEEP_HASH[PROJ] if CHANNEL == "Hgg" else PROVENANCE_HASH
    print("R5_PROVENANCE", CHANNEL, PROJ, len(provenance), flush=True)
    print("R5_INPUT_SHA256", RUN_HASH, flush=True)
    print("R5_CURRENT_PROVENANCE_SHA256", PROVENANCE_HASH, flush=True)
    if CHANNEL == "Hgg":
        print("R5_REUSE_COMPLETED_SWEEP", RUN_HASH,
              "gate_only_code_change=True", flush=True)
    real = _checkpointed("real", real_jobs, _real_worker)
    endpoint = _checkpointed("endpoint", residue_jobs, _residue_worker)
    raw = {k: real[k] - endpoint[k]/s23 for k in (-2, -1, 0)}
    kc = _prefactor_coefficients()
    ct = _ct_coefficients()
    # NO POLE REDUCTION HERE.  The regular sector is finite by construction:
    # s23^{-1-eps}[F(s23) - F(0)] has no pole, so eps -> 0 is taken directly
    # -- exactly the argument the COMPLETED channels' R5 used ("the terms
    # only have to be added, no series at all").  The pole coefficients are
    # still needed as EXPRESSIONS, because the O(eps) part of the prefactor
    # multiplies raw[-1] into the finite answer, but they never need to be
    # reduced or proved zero: that is a CHECK, and all pole checks are
    # deferred to the single summed-level gate.
    #
    # Reducing them here was a monolithic serial `cancel(together(...))`
    # that measured CPU/wallclock = 1.0-1.07, i.e. one core busy and
    # fifteen idle, and dominated the whole task.  Removing it lets each
    # task finish when its parallel sweeps finish.
    pole2_expression = kc.get(0, 0)*raw[-2]
    pole1_expression = kc.get(0, 0)*raw[-1] + ct.get(-1, 0)
    pole2, pole1 = pole2_expression, pole1_expression
    if CHANNEL == "Hgg":
        # Hgg is a pure-real mixing channel, so its own Eq. (46) PDF+FF
        # counterterms must cancel the remaining collinear pole.  Unlike a
        # generic charge channel, there is no virtual/cross-channel partner.
        pole2 = _exact_zero(pole2_expression, "Hgg eps^-2")
        pole1 = _exact_zero(pole1_expression, "Hgg eps^-1")
        if pole2 != 0 or pole1 != 0:
            rejected = os.path.join(CACHE, "Hgg_R5_%s_REJECTED.pkl" % PROJ)
            _atomic(rejected, {"version": VERSION, "input_sha256": RUN_HASH,
                               "pole2": pole2, "pole1": pole1})
            raise AssertionError("Hgg regular poles do not cancel exactly")
    # Do not traverse the unreduced trees merely to print count_ops.  On the
    # production Hgg expressions that diagnostic can cost longer than the
    # actual coefficient sweep and adds no validation evidence.
    print("R5_POLES_RECORDED %s %s reduced=%s"
          % (CHANNEL, PROJ, CHANNEL == "Hgg"), flush=True)
    finite = (kc.get(0, 0)*raw[0] + kc.get(1, 0)*raw[-1]
              + ct.get(0, 0))
    # Producers use equivalent Symbol objects with different assumptions and
    # mix CF with Nc.  Canonicalize these identities in the finite artifact as
    # well as in the Hgg pole proof; this changes representation, not physics.
    from Hgg_R5_quadratic_reduce import canonical_symbols
    finite = canonical_symbols(finite)
    finite_symbols = {symbol.name: symbol for symbol in finite.free_symbols}
    if "CF" in finite_symbols and "Nc" in finite_symbols:
        finite = finite.xreplace({
            finite_symbols["CF"]:
            (finite_symbols["Nc"]**2 - 1)/(2*finite_symbols["Nc"])})
    raw_path = os.path.join(CACHE, "%s_R5_%s_raw.pkl" % (CHANNEL, PROJ))
    _atomic(raw_path, {
        "version": VERSION,
        "input_sha256": RUN_HASH,
        "current_provenance_sha256": PROVENANCE_HASH,
        "gate_code_sha256": _sha(os.path.join(
            HERE, "Hgg_R5_quadratic_reduce.py")),
        "pole2_expression": pole2_expression,
        "pole1_expression": pole1_expression,
        "pole2": pole2, "pole1": pole1, "finite": finite,
        "coordinates": {
            "R5S": "Q2*(xi/x - 1)",
            "R5M": "PHT**2 + z**2*R5S"}})
    # Poles are NOT required to vanish per channel -- see _exact_zero.  Only
    # genuine corruption is fatal.
    if finite.has(eps) or finite.has(sp.Float, sp.zoo, sp.nan, sp.oo, -sp.oo):
        raise AssertionError("invalid finite %s R5 expression" % CHANNEL)
    output = os.path.join(CACHE, "%s_R5_%s.pkl" % (CHANNEL, PROJ))
    _atomic(output, {"version": VERSION, "projection": PROJ,
                     "input_sha256": RUN_HASH,
                     "current_provenance_sha256": PROVENANCE_HASH,
                     "gate_code_sha256": _sha(os.path.join(
                         HERE, "Hgg_R5_quadratic_reduce.py")),
                     "regular": finite,
                     "pole2_unreduced": pole2, "pole1_unreduced": pole1,
                     "poles_reduced": CHANNEL == "Hgg",
                     "provisional_pending_cross_channel_gate": CHANNEL != "Hgg",
                     "elapsed_seconds": time.time() - started})
    print("%s_R5_EXACT_DONE" % CHANNEL.upper(), PROJ, "elapsed",
          time.time() - started, flush=True)


if __name__ == "__main__":
    main()
