(* Kira reduction of the exact two-cut targets generated by S03. *)
$HistoryLength = 0;
$FeynCalcStartupMessages = False;
Get["FeynCalc`"];
root = DirectoryName[$InputFileName];
gate[name_, condition_] := If[TrueQ[condition], Print["PASS: ", name],
  Print["FAIL: ", name]; Quit[1]];
put[value_, file_] := (Put[value, file <> ".tmp"];
  RenameFile[file <> ".tmp", file, OverwriteTarget -> True]);
geometry = Get[FileNameJoin[{root, "s02_result.wl"}]];
mapping = Get[FileNameJoin[{root, "s03_result.wl"}]];
gate["accepted real mapping and geometry identity", TrueQ[mapping["Accepted"]] &&
  mapping["GeometryHash"] === FileHash[FileNameJoin[{root, "s02_result.wl"}], "SHA256"] &&
  mapping["SourceHash"] === FileHash[FileNameJoin[{root, "s03_real_families.wl"}], "SHA256"]];
kira = FileNameJoin[{root, "software", "kira-3.1"}];
fermat = FileNameJoin[{root, "software", "fermat", "Ferl7", "fer64"}];
gate["dedicated Kira and Fermat binaries exist", FileExistsQ[kira] && FileExistsQ[fermat]];
SetEnvironment["FERMATPATH" -> fermat];
sourceHash = FileHash[$InputFileName, "SHA256"];
inputHash = Hash[{sourceHash, FileHash[FileNameJoin[{root, "s03_result.wl"}], "SHA256"],
  mapping["GeometryHash"], FileHash[kira, "SHA256"], FileHash[fermat, "SHA256"]}, "SHA256"];
work = FileNameJoin[{root, "common", "s04_kira_real", IntegerString[inputHash, 16]}];
config = FileNameJoin[{work, "config"}];
If[!DirectoryQ[config], CreateDirectory[config, CreateIntermediateDirectories -> True]];
targets = mapping["Targets"];
names = Sort[DeleteDuplicates[targets[[All, 1]]]];
families = KeyTake[geometry["Families"], names];
text[expression_] := StringReplace[ToString[InputForm[expression]], Whitespace -> ""];
csv[list_] := "[" <> StringRiffle[text /@ list, ","] <> "]";
integralText[integral_] := integral[[1]] <> csv[integral[[2]]];
external = Take[geometry["BasisMomenta"], Length[geometry["BasisMomenta"]] -
  Length[geometry["CutMomenta"]] + 1];
externalGram = geometry["CommonGram"][[Range[Length[external]], Range[Length[external]]]];
invariants = Sort[DeleteDuplicates[Cases[externalGram,
  symbol_Symbol /; Context[symbol] === "Global`", Infinity]]];
(* Fermat requires lower-case variable names. This is a name change only. *)
exportRules = {Q2 -> q2};
importRules = Reverse /@ exportRules;
gate["invariant rename is invertible", (invariants /. exportRules /. importRules) === invariants];
kinematics = {"kinematics:", "  incoming_momenta: " <> csv[external],
  "  outgoing_momenta: []", "  kinematic_invariants:"};
kinematics = Join[kinematics, ("    - [" <> text[# /. exportRules] <> ", 2]" & /@ invariants),
  {"  scalarproduct_rules:"}, Flatten[Table[
    "    - [[" <> text[external[[i]]] <> "," <> text[external[[j]]] <> "], " <>
      text[externalGram[[i, j]] /. exportRules] <> "]",
    {i, Length[external]}, {j, i, Length[external]}]]];
Export[FileNameJoin[{config, "kinematics.yaml"}], StringRiffle[kinematics, "\n"] <> "\n", "Text"];
familyLines = {"integralfamilies:"};
reductions = {};
preferred = {};
bounds = <||>;
Do[
  spec = families[name];
  actual = Select[targets, #[[1]] === name &][[All, 2]];
  positiveSums = Total[Select[#, # > 0 &]] & /@ actual;
  negativeSums = -Total[Select[#, # < 0 &]] & /@ actual;
  sectors = Sort[DeleteDuplicates[Total[MapIndexed[
    If[#1 > 0, 2^(First[#2] - 1), 0] &, #]] & /@ actual]];
  topSectors = Select[sectors, Function[sector, !AnyTrue[DeleteCases[sectors, sector],
    BitAnd[sector, #] === sector &]]];
  rBound = Max[positiveSums] + Length[spec["LoopMomenta"]];
  sBound = Max[negativeSums];
  AssociateTo[bounds, name -> <|"r" -> rBound, "s" -> sBound,
    "Sectors" -> sectors, "TopSectors" -> topSectors, "TargetCount" -> Length[actual]|>];
  familyLines = Join[familyLines, {"  - name: " <> name,
    "    loop_momenta: " <> csv[spec["LoopMomenta"]],
    "    top_level_sectors: " <> csv[topSectors], "    propagators:"},
    MapThread["      - [\"" <> text[#1] <> "\", " <> text[#2] <> "]" &,
      {spec["PropagatorMomenta"], spec["PropagatorMassesSquared"]}],
    {"    cut_propagators: " <> csv[spec["CutPositions"]]}];
  AppendTo[reductions, "        - {topologies: [" <> name <> "], sectors: " <>
    csv[topSectors] <> ", r: " <> text[rBound] <> ", s: " <> text[sBound] <> "}"];
  preferred = Join[preferred, Table[CutIntegral[name,
    Table[If[MemberQ[spec["CutPositions"], i] || MemberQ[support, i], 1, 0],
      {i, Length[spec["PropagatorMomenta"]]}]],
    {support, Subsets[Complement[Range[Length[spec["PropagatorMomenta"]]], spec["CutPositions"]]]}]],
  {name, names}];
Export[FileNameJoin[{config, "integralfamilies.yaml"}], StringRiffle[familyLines, "\n"] <> "\n", "Text"];
Export[FileNameJoin[{work, "targets"}], StringRiffle[integralText /@ targets, "\n"] <> "\n", "Text"];
Export[FileNameJoin[{work, "preferred"}], StringRiffle[integralText /@ preferred, "\n"] <> "\n", "Text"];
jobs = Join[{"jobs:", "  - reduce_sectors:", "      reduce:"}, reductions,
  {"      select_integrals:", "        select_mandatory_list:", "          - [targets]",
   "      preferred_masters: preferred", "      run_initiate: true",
   "      run_triangular: true", "      run_back_substitution: true",
   "  - kira2math:", "      target:", "        - [targets]"}];
Export[FileNameJoin[{work, "jobs.yaml"}], StringRiffle[jobs, "\n"] <> "\n", "Text"];
put[<|"InputHash" -> inputHash, "SourceHash" -> sourceHash, "Bounds" -> bounds,
  "Families" -> families, "Targets" -> targets, "PreferredCandidates" -> preferred,
  "ExportRules" -> exportRules, "ImportRules" -> importRules,
  "CutEnergyConditions" -> geometry["CutEnergyConditions"]|>, FileNameJoin[{work, "s04_configuration.wl"}]];
Print["KIRA_START ", work, " target count ", Length[targets], " bounds ", InputForm[bounds]];
run = RunProcess[{kira, "--parallel=2", "jobs.yaml"}, All, ProcessDirectory -> work];
Export[FileNameJoin[{work, "s04_kira_stdout.log"}], run["StandardOutput"], "Text"];
Export[FileNameJoin[{work, "s04_kira_stderr.log"}], run["StandardError"], "Text"];
Print[StringTake[run["StandardOutput"], -Min[12000, StringLength[run["StandardOutput"]]]]];
If[run["StandardError"] =!= "", Print[run["StandardError"]]];
gate["Kira completed", run["ExitCode"] === 0];
ruleFiles = Sort[FileNames["kira_*.m", FileNameJoin[{work, "results"}], Infinity]];
gate["Kira exported symbolic rules", Length[ruleFiles] > 0];
rules = DeleteDuplicates[Flatten[Get /@ ruleFiles]];
gate["Kira output consists of rules", MatchQ[rules, {__Rule}]];
heads = Symbol /@ names;
toCut[expression_] := expression /. (HoldPattern[h_[indices__Integer]] /; MemberQ[heads, h]) :>
  CutIntegral[SymbolName[h], {indices}];
masterFile = FileNameJoin[{work, "tmp", Last[names], "masters"}];
gate["final Kira master inventory exists", FileExistsQ[masterFile]];
declaredMasters = toCut[ToExpression /@ StringCases[Import[masterFile, "Text"],
  RegularExpression["R[0-9]+\\[[0-9, -]+\\]"]]];
gate["nonempty final Kira master inventory", MatchQ[declaredMasters, {__CutIntegral}]];
rules = toCut[rules] /. importRules /. d -> D;
missingTargets = Complement[targets, First /@ rules];
gate["targets without explicit rules are declared masters",
  Complement[missingTargets, declaredMasters] === {}];
rules = Join[rules, (# -> # & /@ missingTargets)];
gate["each target has a reduction rule", Complement[targets, First /@ rules] === {}];
gate["rules have unique targets", DuplicateFreeQ[First /@ rules]];
masters = Sort[DeleteDuplicates[Cases[Last /@ rules, _CutIntegral, Infinity]]];
gate["every rule ends in Kira's final master inventory",
  Complement[masters, declaredMasters] === {}];
gate["both cut propagators survive in every master", And @@
  (And @@ (# > 0 & /@ #[[2, families[#[[1]]]["CutPositions"]]]) & /@ masters)];
gate["rule coefficients are rational in symbolic dimension and invariants",
  FreeQ[rules, _Real | $Failed | $Aborted]];
resultFile = FileNameJoin[{root, "s04_result.wl"}];
put[<|"Rules" -> rules, "Masters" -> masters, "Targets" -> targets,
  "Bounds" -> bounds, "Families" -> families, "SourceHash" -> sourceHash,
  "InputHash" -> inputHash, "MappingHash" -> FileHash[FileNameJoin[{root, "s03_result.wl"}], "SHA256"],
  "KiraHash" -> FileHash[kira, "SHA256"], "FermatHash" -> FileHash[fermat, "SHA256"],
  "RuleFiles" -> ruleFiles, "WorkDirectory" -> work, "Accepted" -> True,
  "CutEnergyConditions" -> geometry["CutEnergyConditions"],
  "MasterEvaluationPerformed" -> False|>, resultFile];
Do[put[<|"Channel" -> channel, "RealMappingHash" -> mapping["Channels"][channel]["SHA256"],
  "SharedReduction" -> "../s04_result.wl", "SharedReductionHash" -> FileHash[resultFile, "SHA256"],
  "Accepted" -> True, "MasterEvaluationPerformed" -> False|>,
  FileNameJoin[{root, channel, "s04_result.wl"}]], {channel, Keys[mapping["Channels"]]}];
Print["S04_SUCCESS: ", Length[targets], " targets reduced to ", Length[masters], " cut masters."];
Print["MASTERS ", InputForm[masters]];
Quit[0];
