jobs:
 - reduce_sectors:
    reduce:
      - {topologies: [topo7], sectors: [127], r: 7, s: 5, d: 0}
      - {topologies: [topo7], sectors: [78], r: 5, s: 3, d: 1}
    select_integrals:
      select_mandatory_list:
        - [seeds7]
    run_initiate: input
    truncate_sp: 
      - {l: 3}
