jobs:
 - reduce_sectors:
    reduce:
      - {topologies: [doublePentagon], sectors: [255], r: 8, s: 5, d: 0}
      - {topologies: [doublePentagon], sectors: [167], r: 8, s: 3, d: 0}
      #- {topologies: [doublePentagon], sectors: [255], r: 9, s: 5, d: 1}
      #- {topologies: [doublePentagon], sectors: [255], r: 13, s: 5, d: 5}
    select_integrals:
      select_mandatory_list:
         - [integrals-8.5.0]
         #- [integral-9.5.1] 
         #- [integrals-13.5.5] 
    run_initiate: true
    run_firefly: true
    truncate_sp: 
     - {l: 4}
      #- {l: 3} # Lazy choice
