jobs:
 - reduce_sectors:
    reduce:
      - {topologies: [hex], sectors: [511], r: 9, s: 5, d: 0}
      - {topologies: [hex], sectors: [103], r: 8, s: 3, d: 1}
      - {topologies: [hex], sectors: [222], r: 8, s: 3, d: 1}
      - {topologies: [hex], sectors: [215], r: 8, s: 3, d: 1}
      - {topologies: [hex], sectors: [214], r: 8, s: 2, d: 1}
      - {topologies: [hex], sectors: [220], r: 8, s: 2, d: 1}
      - {topologies: [hex], sectors: [206], r: 8, s: 2, d: 1}
      - {topologies: [hex], sectors: [218], r: 8, s: 2, d: 1}
      - {topologies: [hex], sectors: [211], r: 8, s: 2, d: 1}
      - {topologies: [hex], sectors: [213], r: 8, s: 2, d: 0}
      - {topologies: [hex], sectors: [115], r: 8, s: 2, d: 0}
      - {topologies: [hex], sectors: [122], r: 8, s: 2, d: 0}
      - {topologies: [hex], sectors: [110], r: 8, s: 2, d: 0}
      - {topologies: [hex], sectors: [173], r: 8, s: 2, d: 0}
      - {topologies: [hex], sectors: [231], r: 8, s: 3, d: 0}
      - {topologies: [hex], sectors: [167], r: 8, s: 2, d: 0}
    select_integrals:
      select_mandatory_list:
        - [integrals-9.5.0]
    run_initiate: true
    run_firefly: true
    truncate_sp:
      - {l: 5}
